version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: twitter_clone_mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: twitter-clone
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
